<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CoursesPrograms</name>
   <tag></tag>
   <elementGuidId>9d1f19f7-435d-4dd3-877e-551402d4ec79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sm-17182685828675286-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sm-17182685828675286-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Courses/Programs&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f37faab-e98d-4fea-a0a2-f9e20e6916bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6c7b31ae-680c-4039-a3ed-44cb38a34290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle has-submenu highlighted</value>
      <webElementGuid>43169286-3a17-4ed7-ab73-10865c4e7c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6197d6ad-3f7e-4f6d-bebb-cdfba7191792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42c4b7d1-4c0e-46c1-b863-3ba6ad83c6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sm-17182685828675286-3</value>
      <webElementGuid>91c6dda6-8c80-44f3-a04b-754ca0af5a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sm-17182685828675286-4</value>
      <webElementGuid>7833c060-38a5-4f16-893c-ed0c3026b58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Courses/Programs </value>
      <webElementGuid>ad18454f-b6c9-4267-a76d-275f2a99bbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17182685828675286-3&quot;)</value>
      <webElementGuid>af4c11b7-f3be-4237-ae33-059a9670999a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sm-17182685828675286-3']</value>
      <webElementGuid>1c87864c-4ae6-4637-8cf8-2a7b75da189b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bootsterMenu']/ul/li[3]/a</value>
      <webElementGuid>f8ff0296-c0e8-4b10-b150-901f88019de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Courses/Programs')]</value>
      <webElementGuid>b4447e30-9275-400a-9940-6e374b1b5332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From HOD Desk'])[1]/following::a[1]</value>
      <webElementGuid>cfc9b0c1-bb95-471b-be80-e007963c7e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objectives'])[1]/following::a[2]</value>
      <webElementGuid>2d6f37b4-72b8-45c0-813e-c25f9ff6909d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.Sc. (Biochemistry)'])[1]/preceding::a[1]</value>
      <webElementGuid>7739270c-d2de-4875-a94f-aeba6ff300a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.Phil. (Biochemistry)'])[1]/preceding::a[2]</value>
      <webElementGuid>6c9890dc-3475-4fff-a07b-48e43231254f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Courses/Programs']/parent::*</value>
      <webElementGuid>2343d074-8e8b-4137-bcc0-bd2602c759d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>cae15027-8ba9-44c5-8c29-67cb2eabd11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>b440d2c9-6e47-4323-8466-38ccb7ca4188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'sm-17182685828675286-3' and (text() = 'Courses/Programs ' or . = 'Courses/Programs ')]</value>
      <webElementGuid>b71114b4-ebb7-4159-8ad2-139315c1706a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
