<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_,_img-responsive</name>
   <tag></tag>
   <elementGuidId>1848e5b6-2811-4bc4-939f-db4a8da3d9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnn_ctr16187_HtmlModule_lblContent']/div/p/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > a > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admissions-2024&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c1ef79e2-8226-43b3-a5fb-d1b70fc224c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Admissions-2024</value>
      <webElementGuid>89bb94e2-90e2-48a2-a0f0-0b6700d210fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>71a5deea-1002-4c76-bd06-6a42c2902907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/portals/0/admission-2024.png</value>
      <webElementGuid>4123306c-37af-4310-879e-f734edf60341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Admissions-2024</value>
      <webElementGuid>d8afe8f8-9c93-4a85-8d5d-1a551c2763d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnn_ctr16187_HtmlModule_lblContent&quot;)/div[@class=&quot;col-md-12&quot;]/p[1]/a[1]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>a09bd924-8cbd-4f7e-a60d-3f346086f9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnn_ctr16187_HtmlModule_lblContent']/div/p/a/img</value>
      <webElementGuid>d3d64a67-f1a9-4239-9e0d-e3c9187b852a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Admissions-2024']</value>
      <webElementGuid>ec067f76-a53c-4e75-b25f-22b9674dc205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a/img</value>
      <webElementGuid>6d3f47b9-8d8c-4b55-b9b6-74a607fc206f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Admissions-2024' and @src = '/portals/0/admission-2024.png' and @title = 'Admissions-2024']</value>
      <webElementGuid>b73c32de-c959-4e48-ab4e-34fc3f3550e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
