<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ph.D. Entrance Exam Notification- 2021</name>
   <tag></tag>
   <elementGuidId>3c92005f-84b9-4bb5-a9c1-3ea7deab338a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnn_ctr569_HtmlModule_lblContent']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dnn_ctr569_HtmlModule_lblContent > ul > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ph.D. Entrance Exam Notification- 2021&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55b5fddf-e67a-415e-b83f-aa62072824a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://online.bamu.ac.in/unic/pet-2021/</value>
      <webElementGuid>7b3bb61b-eae3-470c-aaae-9d53ad517ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>df16d67b-f917-43f5-8b1a-d8b560331cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ph.D. Entrance Exam Notification- 2021</value>
      <webElementGuid>61eb1ca6-be37-4601-8335-ee2893641e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnn_ctr569_HtmlModule_lblContent&quot;)/ul[1]/li[2]/a[1]</value>
      <webElementGuid>6df894ad-daa2-492f-8f48-2b7026adacae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnn_ctr569_HtmlModule_lblContent']/ul/li[2]/a</value>
      <webElementGuid>b8483c0b-8a0b-4100-baf9-8bdc1cdc9fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ph.D. Entrance Exam Notification- 2021')]</value>
      <webElementGuid>2329d519-04e8-4b4b-96ae-8a25fe2bc007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UGC Regulation - 2016-17'])[1]/following::a[1]</value>
      <webElementGuid>16b87b18-d4a0-44ad-bbf6-99476577f3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Students/Researchers'])[1]/following::a[2]</value>
      <webElementGuid>78dcff63-745c-4f73-a069-6b4336d83a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Colleges/Institutions'])[1]/preceding::a[1]</value>
      <webElementGuid>dbfe7a42-ac35-4f11-93da-9028ea5b3a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Centre Guidelines'])[1]/preceding::a[1]</value>
      <webElementGuid>b4c6fb8c-19c0-4865-a94a-de1fb94362c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ph.D. Entrance Exam Notification- 2021']/parent::*</value>
      <webElementGuid>eb352878-be2d-4f3a-856a-82cd45745836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://online.bamu.ac.in/unic/pet-2021/')]</value>
      <webElementGuid>8f616670-0eb6-4c7a-9f31-bebdc4adae03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>2864c940-e2c1-4769-b632-2920407d6332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://online.bamu.ac.in/unic/pet-2021/' and (text() = 'Ph.D. Entrance Exam Notification- 2021' or . = 'Ph.D. Entrance Exam Notification- 2021')]</value>
      <webElementGuid>fe6b9769-849c-4f94-85e5-9ff5c75f85f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
