<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shodhganga - Thesis Repository</name>
   <tag></tag>
   <elementGuidId>d4b5ee5a-c556-47b5-9f15-b47862f3a4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnn_ctr570_HtmlModule_lblContent']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dnn_ctr570_HtmlModule_lblContent > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Shodhganga - Thesis Repository&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4f4c3b3-e543-4d5f-bcf1-0a904ab64f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://shodhganga.inflibnet.ac.in/</value>
      <webElementGuid>6d3c856c-7cd8-4ace-b44d-bd8df1e94f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a99c2871-8435-443e-ae38-d8f36da8a9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shodhganga - Thesis Repository</value>
      <webElementGuid>4458d2d5-fa87-4b6c-b0de-081fe9d72bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnn_ctr570_HtmlModule_lblContent&quot;)/ul[1]/li[1]/a[1]</value>
      <webElementGuid>886c424c-923f-48c4-9c02-baed9a5fb64a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnn_ctr570_HtmlModule_lblContent']/ul/li/a</value>
      <webElementGuid>d17eb4e1-14e8-40ae-aaf2-73fa3bb3c1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shodhganga - Thesis Repository')]</value>
      <webElementGuid>0cc2c8c4-246c-47a8-aab9-fd4bd52d29c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Resources'])[1]/following::a[1]</value>
      <webElementGuid>a736f354-545d-4c3d-9e86-60f56a9026c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Methodology For Ranking of Universities'])[1]/following::a[2]</value>
      <webElementGuid>72a7d0c1-557c-4a2c-982d-7877fb8772d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Research Photo Gallery'])[1]/preceding::a[1]</value>
      <webElementGuid>c2d033a5-b1dc-43b7-8091-d91834a1087c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Resource Center'])[1]/preceding::a[2]</value>
      <webElementGuid>a2ddc69c-def7-4101-899c-86f4d980c641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shodhganga - Thesis Repository']/parent::*</value>
      <webElementGuid>2ed847dc-299c-4f83-84bb-a81611440ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://shodhganga.inflibnet.ac.in/']</value>
      <webElementGuid>221a5fb1-fdd2-4307-9e81-5757895104a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>835b0e3e-4fb2-4628-977b-31d61220606b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://shodhganga.inflibnet.ac.in/' and (text() = 'Shodhganga - Thesis Repository' or . = 'Shodhganga - Thesis Repository')]</value>
      <webElementGuid>de997e66-f12d-4247-b000-eb4366a60c2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
