<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2c3d67ee-a17d-49e2-8801-e06ea8849a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnn_ctr598_HtmlModule_lblContent']/p[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p:nth-child(2) > img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99bcbaa5-bacf-46e1-a5b3-4fe0f37e2100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/portals/0/mgmtsci-background.jpg</value>
      <webElementGuid>604b20b8-84d0-4efe-bd8f-b156e05b8407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnn_ctr598_HtmlModule_lblContent&quot;)/p[2]/img[1]</value>
      <webElementGuid>e635c4e3-cf25-416f-b8c5-76bc1faf1621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnn_ctr598_HtmlModule_lblContent']/p[2]/img</value>
      <webElementGuid>c541844e-36f9-48b5-b19f-bf762cba37b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/img</value>
      <webElementGuid>779950ab-a859-4957-ab17-03b50ecc55c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/portals/0/mgmtsci-background.jpg']</value>
      <webElementGuid>ec2ca67a-3430-42e9-9072-5d320df67125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
