<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Circulars</name>
   <tag></tag>
   <elementGuidId>956b298d-c1b7-42d4-b10c-85f86062a75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnn_ctr534_HtmlModule_lblContent']/ul[3]/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-of-type(3) > li:nth-of-type(6) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Circulars&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d62b0d05-467d-40e0-b871-fea2fc7e1a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/LinkClick.aspx?link=3642&amp;portalid=0</value>
      <webElementGuid>8f957074-1ee0-45a8-a558-66d278ff9a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Circulars</value>
      <webElementGuid>58c67682-7342-4ee1-af1c-81f534c4cd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnn_ctr534_HtmlModule_lblContent&quot;)/ul[3]/li[6]/a[1]</value>
      <webElementGuid>f54f52c0-83d5-4c8f-a6b4-f3ad728455e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnn_ctr534_HtmlModule_lblContent']/ul[3]/li[6]/a</value>
      <webElementGuid>e6642bdf-22cd-42f5-9aa3-b6964c777de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Circulars')]</value>
      <webElementGuid>72f85718-3160-4604-a8c1-cbb007946992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Committee'])[1]/following::a[1]</value>
      <webElementGuid>d4b3fe11-18f9-43ee-8b8f-4da71ceff4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance &amp; Accounts Committee'])[1]/following::a[2]</value>
      <webElementGuid>a4b055b1-5c17-4677-8209-bc5dec077285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrar Office'])[1]/preceding::a[2]</value>
      <webElementGuid>26f15d75-d183-4f9a-b4f8-e6efc49e6042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrar Office'])[2]/preceding::a[2]</value>
      <webElementGuid>68d7139e-4355-4142-8d61-5eb3c70409f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Circulars']/parent::*</value>
      <webElementGuid>b11f1e35-6af2-4468-b18e-2626f1e0cfa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/LinkClick.aspx?link=3642&amp;portalid=0')]</value>
      <webElementGuid>8b697cbd-7fbc-4a90-bb5a-062e63954e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li[6]/a</value>
      <webElementGuid>486c687d-4d74-4fa7-8f13-499d941ec650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/LinkClick.aspx?link=3642&amp;portalid=0' and (text() = 'Circulars' or . = 'Circulars')]</value>
      <webElementGuid>b00782bb-463a-4f30-83d8-a54c719c3bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
